# Generated by Django 4.2.22 on 2025-07-20 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_project_user_task_user_alter_resume_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='begin_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
