# Generated by Django 5.0.4 on 2026-01-31 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_recurringtask'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='recurring_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='api.recurringtask'),
        ),
    ]
