# Generated by Django 5.0.4 on 2026-01-31 16:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_task_recurring_task'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='task',
            constraint=models.UniqueConstraint(fields=('recurring_task', 'begin_date'), name='uniq_task_recurring_task_begin_date'),
        ),
    ]
