# Generated by Django 5.0.4 on 2026-02-19 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_task_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.CharField(choices=[('task', 'Task'), ('meeting', 'Meeting'), ('note', 'Note')], default='medium', max_length=10),
        ),
    ]
