# Generated by Django 5.0.4 on 2026-03-01 01:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_task_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringTaskException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('type', models.CharField(choices=[('skip', 'Skip')], default='skip', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recurring_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exceptions', to='api.recurringtask')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='recurringtaskexception',
            constraint=models.UniqueConstraint(fields=('user', 'recurring_task', 'date', 'type'), name='uniq_recurring_exception_per_day'),
        ),
    ]
