# Generated by Django 4.2.29 on 2026-03-29 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_recurringtaskexception_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurringtask',
            name='frequency',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('biweekly', 'Bi-weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly')], max_length=10),
        ),
    ]
