# Generated by Django 4.2.29 on 2026-04-11 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_project_description_project_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='role',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
