# Generated by Django 4.2.29 on 2026-04-12 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_add_role_to_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='deadline_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
