# Generated by Django 4.2.30 on 2026-04-12 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_add_calendar_blacklist'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='title',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
