# Generated by Django 4.2.30 on 2026-05-01 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_resumeprofile_workexperience_skill_education'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('summary', models.TextField(blank=True, default='')),
                ('suggestions', models.JSONField(default=list)),
                ('accomplishments', models.JSONField(default=list)),
                ('bullet_rewrites', models.JSONField(default=dict)),
                ('analyzed_at', models.DateTimeField(auto_now=True)),
                ('resume_fingerprint', models.CharField(blank=True, default='', max_length=64)),
                ('resume', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='api.resume')),
            ],
            options={
                'verbose_name': 'Resume Analysis',
                'verbose_name_plural': 'Resume Analyses',
            },
        ),
    ]
